language: go
dist: bionic
go:
  - 1.13.x

before_script:
  - export PATH=$HOME/protobuf/bin:$PATH
  - make install-tools

install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && curl -LO 'https://github.com/google/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip'
    && unzip protoc-3.11.2-linux-x86_64.zip
    && popd
  - gem install grpc grpc-tools

matrix:
  include:
    - name: test
      script:
        - make test
    - name: fmt
      script:
        - make ci-fmt
    - name: proto
      script:
        - make ci-proto
