language: go
dist: bionic
go:
  - 1.13.x

before_script:
  - make install-tools

matrix:
  include:
    - name: test
      script:
        - make test
    - name: fmt
      script:
        - make ci-fmt
    - name: proto
      script:
        - make ci-proto
